# Generated by Django 4.1.3 on 2023-01-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_contact_email_remove_contact_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicesmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=250)),
            ],
        ),
    ]
