# Generated by Django 4.1.3 on 2023-01-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_servicesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='pricemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(max_length=100)),
                ('offer', models.CharField(max_length=100)),
            ],
        ),
    ]
