# Generated by Django 4.1.3 on 2023-01-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_pricemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricemodel',
            name='price',
            field=models.IntegerField(),
        ),
    ]
