# Generated by Django 4.1.3 on 2023-01-28 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_pricemodel_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricemodel',
            unique_together={('price', 'offer')},
        ),
    ]
